// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAweY8bfv9dhoASuyVEVYspV4_s4bFbjEc',
    appId: '1:705258727806:web:393febdf287cc1f046eb2f',
    messagingSenderId: '705258727806',
    projectId: 'uhca-20800',
    authDomain: 'uhca-20800.firebaseapp.com',
    databaseURL: 'https://uhca-20800-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uhca-20800.firebasestorage.app',
    measurementId: 'G-H827KGWBWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgH4BkrHESLqC3pJ0Skn8lgk7LWJQwZdA',
    appId: '1:705258727806:android:1f73e29262863a3846eb2f',
    messagingSenderId: '705258727806',
    projectId: 'uhca-20800',
    databaseURL: 'https://uhca-20800-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uhca-20800.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd_fsuDqeEM4EILkWCvPIkgIR60UzeuEc',
    appId: '1:705258727806:ios:1fafb2d2e0fd742146eb2f',
    messagingSenderId: '705258727806',
    projectId: 'uhca-20800',
    databaseURL: 'https://uhca-20800-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uhca-20800.firebasestorage.app',
    iosBundleId: 'com.example.uhc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd_fsuDqeEM4EILkWCvPIkgIR60UzeuEc',
    appId: '1:705258727806:ios:1fafb2d2e0fd742146eb2f',
    messagingSenderId: '705258727806',
    projectId: 'uhca-20800',
    databaseURL: 'https://uhca-20800-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uhca-20800.firebasestorage.app',
    iosBundleId: 'com.example.uhc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAweY8bfv9dhoASuyVEVYspV4_s4bFbjEc',
    appId: '1:705258727806:web:1ac0612fa5cff04646eb2f',
    messagingSenderId: '705258727806',
    projectId: 'uhca-20800',
    authDomain: 'uhca-20800.firebaseapp.com',
    databaseURL: 'https://uhca-20800-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'uhca-20800.firebasestorage.app',
    measurementId: 'G-FVYNT4ZZ57',
  );
}
