import 'package:flutter/foundation.dart';

/// Status of an assistant turn or message from the backend.
enum AssistantMessageStatus {
  ready,
  clarify,
  outOfScope,
  dailyLimit,
  throttled,
  unavailable,
  disabled,
  cancelled,
  unknown;

  static AssistantMessageStatus fromString(String? value) {
    if (value == null) return AssistantMessageStatus.unknown;
    switch (value.trim().toLowerCase()) {
      case 'ready':
        return AssistantMessageStatus.ready;
      case 'clarify':
        return AssistantMessageStatus.clarify;
      case 'out_of_scope':
        return AssistantMessageStatus.outOfScope;
      case 'daily_limit':
        return AssistantMessageStatus.dailyLimit;
      case 'throttled':
        return AssistantMessageStatus.throttled;
      case 'unavailable':
        return AssistantMessageStatus.unavailable;
      case 'disabled':
        return AssistantMessageStatus.disabled;
      case 'cancelled':
        return AssistantMessageStatus.cancelled;
      default:
        return AssistantMessageStatus.unknown;
    }
  }

  String toBackendString() {
    switch (this) {
      case AssistantMessageStatus.ready:
        return 'ready';
      case AssistantMessageStatus.clarify:
        return 'clarify';
      case AssistantMessageStatus.outOfScope:
        return 'out_of_scope';
      case AssistantMessageStatus.dailyLimit:
        return 'daily_limit';
      case AssistantMessageStatus.throttled:
        return 'throttled';
      case AssistantMessageStatus.unavailable:
        return 'unavailable';
      case AssistantMessageStatus.disabled:
        return 'disabled';
      case AssistantMessageStatus.cancelled:
        return 'cancelled';
      case AssistantMessageStatus.unknown:
        return 'unknown';
    }
  }
}

/// Structured appointment suggestion generated by server schedule matcher.
@immutable
class AssistantOffer {
  final String offerId;
  final String doctorId;
  final String doctorName;
  final String department;
  final String? departmentName;
  final String appointmentDate; // Canonical YYYY-MM-DD
  final String timeSlot; // 'HH:MM - HH:MM' or 'HH:MM'
  final DateTime expiresAt; // 10 minutes from creation (UTC)
  final bool isAvailable;

  const AssistantOffer({
    required this.offerId,
    required this.doctorId,
    required this.doctorName,
    required this.department,
    this.departmentName,
    required this.appointmentDate,
    required this.timeSlot,
    required this.expiresAt,
    required this.isAvailable,
  });

  bool isExpired([DateTime? now]) {
    final reference = (now ?? DateTime.now()).toUtc();
    return !reference.isBefore(expiresAt.toUtc());
  }

  bool isBookable([DateTime? now]) {
    return isAvailable && !isExpired(now);
  }

  static bool isValidCanonicalDate(String dateStr) {
    final match = RegExp(r'^(\d{4})-(\d{2})-(\d{2})$').firstMatch(dateStr);
    if (match == null) return false;
    final y = int.tryParse(match.group(1)!);
    final m = int.tryParse(match.group(2)!);
    final d = int.tryParse(match.group(3)!);
    if (y == null || m == null || d == null) return false;
    if (m < 1 || m > 12 || d < 1 || d > 31) return false;
    final dt = DateTime.utc(y, m, d);
    return dt.year == y && dt.month == m && dt.day == d;
  }

  DateTime? get parsedAppointmentDate {
    if (!isValidCanonicalDate(appointmentDate)) return null;
    try {
      return DateTime.parse('${appointmentDate}T00:00:00Z');
    } catch (_) {
      return null;
    }
  }

  factory AssistantOffer.fromJson(Map<String, dynamic> json) {
    DateTime? parsedExpiresAt;
    try {
      final rawExpires = json['expiresAt'];
      if (rawExpires is String && rawExpires.trim().isNotEmpty) {
        parsedExpiresAt = DateTime.parse(rawExpires).toUtc();
      }
    } catch (_) {
      parsedExpiresAt = null;
    }

    final offerId = (json['offerId'] as String?)?.trim() ?? '';
    final doctorId = (json['doctorId'] as String?)?.trim() ?? '';
    final doctorName = (json['doctorName'] as String?)?.trim() ?? 'Doctor';
    final department = (json['department'] as String?)?.trim() ?? '';
    final departmentName = (json['departmentName'] as String?)?.trim();
    final appointmentDate = (json['appointmentDate'] as String?)?.trim() ?? '';
    final timeSlot = (json['timeSlot'] as String?)?.trim() ?? '';

    // Fail closed: reject malformed IDs, date, timeSlot, or expiry
    final isValid = offerId.isNotEmpty &&
        doctorId.isNotEmpty &&
        department.isNotEmpty &&
        timeSlot.isNotEmpty &&
        appointmentDate.isNotEmpty &&
        isValidCanonicalDate(appointmentDate) &&
        parsedExpiresAt != null;

    final finalExpiresAt = isValid
        ? parsedExpiresAt
        : DateTime.fromMillisecondsSinceEpoch(0, isUtc: true);
    final finalIsAvailable = isValid && json['isAvailable'] == true;

    return AssistantOffer(
      offerId: offerId,
      doctorId: doctorId,
      doctorName: doctorName,
      department: department,
      departmentName: departmentName,
      appointmentDate: appointmentDate,
      timeSlot: timeSlot,
      expiresAt: finalExpiresAt,
      isAvailable: finalIsAvailable,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'offerId': offerId,
      'doctorId': doctorId,
      'doctorName': doctorName,
      'department': department,
      if (departmentName != null) 'departmentName': departmentName,
      'appointmentDate': appointmentDate,
      'timeSlot': timeSlot,
      'expiresAt': expiresAt.toUtc().toIso8601String(),
      'isAvailable': isAvailable,
    };
  }

  AssistantOffer copyWith({
    bool? isAvailable,
    DateTime? expiresAt,
  }) {
    return AssistantOffer(
      offerId: offerId,
      doctorId: doctorId,
      doctorName: doctorName,
      department: department,
      departmentName: departmentName,
      appointmentDate: appointmentDate,
      timeSlot: timeSlot,
      expiresAt: expiresAt ?? this.expiresAt,
      isAvailable: isAvailable ?? this.isAvailable,
    );
  }
}

/// A chat message exchanged in the assistant session.
@immutable
class AssistantChatMessage {
  final String id;
  final String sender; // 'patient' | 'assistant'
  final String text;
  final AssistantMessageStatus status;
  final String? reasonCode;
  final List<String> offerIds;
  final DateTime createdAt;
  final bool isPending; // Local optimistic flag

  const AssistantChatMessage({
    required this.id,
    required this.sender,
    required this.text,
    this.status = AssistantMessageStatus.ready,
    this.reasonCode,
    this.offerIds = const [],
    required this.createdAt,
    this.isPending = false,
  });

  bool get isPatient => sender == 'patient';
  bool get isAssistant => sender == 'assistant';

  factory AssistantChatMessage.fromJson(Map<String, dynamic> json) {
    DateTime parsedCreatedAt;
    try {
      final rawCreated = json['createdAt'];
      if (rawCreated is String) {
        parsedCreatedAt = DateTime.parse(rawCreated);
      } else {
        parsedCreatedAt = DateTime.now();
      }
    } catch (_) {
      parsedCreatedAt = DateTime.now();
    }

    final rawOfferIds = json['offerIds'];
    List<String> offerIds = [];
    if (rawOfferIds is List) {
      offerIds = rawOfferIds.map((e) => e.toString()).toList();
    }

    return AssistantChatMessage(
      id: (json['id'] as String?)?.trim() ?? 'msg_${DateTime.now().millisecondsSinceEpoch}',
      sender: (json['sender'] as String?)?.trim() == 'assistant' ? 'assistant' : 'patient',
      text: (json['text'] as String?) ?? '',
      status: AssistantMessageStatus.fromString(json['status'] as String?),
      reasonCode: json['reasonCode'] as String?,
      offerIds: offerIds,
      createdAt: parsedCreatedAt,
      isPending: false,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'sender': sender,
      'text': text,
      'status': status.toBackendString(),
      if (reasonCode != null) 'reasonCode': reasonCode,
      'offerIds': offerIds,
      'createdAt': createdAt.toUtc().toIso8601String(),
    };
  }
}

/// Result returned from `sendAssistantMessage`.
@immutable
class SendAssistantMessageResult {
  final bool success;
  final AssistantMessageStatus status;
  final String? reasonCode;
  final String message;
  final String replyLanguage;
  final List<AssistantOffer> offers;
  final DateTime? resetAt;
  final int revision;

  const SendAssistantMessageResult({
    required this.success,
    required this.status,
    this.reasonCode,
    required this.message,
    required this.replyLanguage,
    required this.offers,
    this.resetAt,
    required this.revision,
  });

  factory SendAssistantMessageResult.fromJson(Map<String, dynamic> json) {
    DateTime? parsedResetAt;
    final rawResetAt = json['resetAt'];
    if (rawResetAt is String && rawResetAt.trim().isNotEmpty) {
      try {
        parsedResetAt = DateTime.parse(rawResetAt).toUtc();
      } catch (_) {
        parsedResetAt = null;
      }
    }

    final rawOffers = json['offers'];
    List<AssistantOffer> parsedOffers = [];
    if (rawOffers is List) {
      for (final o in rawOffers) {
        if (o is Map) {
          parsedOffers.add(AssistantOffer.fromJson(Map<String, dynamic>.from(o)));
        }
      }
    }

    return SendAssistantMessageResult(
      success: json['success'] == true,
      status: AssistantMessageStatus.fromString(json['status'] as String?),
      reasonCode: json['reasonCode'] as String?,
      message: (json['message'] as String?) ?? '',
      replyLanguage: (json['replyLanguage'] as String?) ?? 'en',
      offers: parsedOffers,
      resetAt: parsedResetAt,
      revision: (json['revision'] as num?)?.toInt() ?? 0,
    );
  }
}

/// Result returned from `getAssistantHistory`.
@immutable
class GetAssistantHistoryResult {
  final bool success;
  final List<AssistantChatMessage> messages;
  final List<AssistantOffer> offers;
  final int revision;
  final DateTime? resetAt;
  final AssistantMessageStatus? status;

  const GetAssistantHistoryResult({
    required this.success,
    required this.messages,
    required this.offers,
    required this.revision,
    this.resetAt,
    this.status,
  });

  factory GetAssistantHistoryResult.fromJson(Map<String, dynamic> json) {
    DateTime? parsedResetAt;
    final rawResetAt = json['resetAt'];
    if (rawResetAt is String && rawResetAt.trim().isNotEmpty) {
      try {
        parsedResetAt = DateTime.parse(rawResetAt).toUtc();
      } catch (_) {
        parsedResetAt = null;
      }
    }

    AssistantMessageStatus? parsedStatus;
    if (json['status'] != null) {
      parsedStatus = AssistantMessageStatus.fromString(json['status'] as String?);
    }

    final rawMessages = json['messages'];
    List<AssistantChatMessage> parsedMessages = [];
    if (rawMessages is List) {
      for (final m in rawMessages) {
        if (m is Map) {
          parsedMessages.add(AssistantChatMessage.fromJson(Map<String, dynamic>.from(m)));
        }
      }
    }

    final rawOffers = json['offers'];
    List<AssistantOffer> parsedOffers = [];
    if (rawOffers is List) {
      for (final o in rawOffers) {
        if (o is Map) {
          parsedOffers.add(AssistantOffer.fromJson(Map<String, dynamic>.from(o)));
        }
      }
    }

    return GetAssistantHistoryResult(
      success: json['success'] == true,
      messages: parsedMessages,
      offers: parsedOffers,
      revision: (json['revision'] as num?)?.toInt() ?? 0,
      resetAt: parsedResetAt,
      status: parsedStatus,
    );
  }
}

/// Result returned from `confirmAssistantAppointment`.
/// Contract: returns success, appointmentId, bookingReference, qrCode ONLY.
@immutable
class ConfirmAssistantAppointmentResult {
  final bool success;
  final String appointmentId;
  final String bookingReference;
  final String? qrCode;

  const ConfirmAssistantAppointmentResult({
    required this.success,
    required this.appointmentId,
    required this.bookingReference,
    this.qrCode,
  });

  bool get isValid => success && appointmentId.isNotEmpty && bookingReference.isNotEmpty;

  factory ConfirmAssistantAppointmentResult.fromJson(Map<String, dynamic> json) {
    final rawSuccess = json['success'] == true;
    final appointmentId = (json['appointmentId'] as String?)?.trim() ?? '';
    final bookingReference = (json['bookingReference'] as String?)?.trim() ?? '';
    final isValidReceipt = rawSuccess && appointmentId.isNotEmpty && bookingReference.isNotEmpty;

    return ConfirmAssistantAppointmentResult(
      success: isValidReceipt,
      appointmentId: appointmentId,
      bookingReference: bookingReference,
      qrCode: json['qrCode'] as String?,
    );
  }
}
