"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.setAdminPermissions = exports.setAdminActiveStatus = exports.rotateSuperAdminSlot = exports.resetAdminPassword = exports.listAdminAuditLogs = exports.forceSignOutUser = exports.deleteAdminAccount = exports.createAdminAccount = exports.changeAdminRole = exports.assignSuperAdminSlot = exports.sendTopicNotification = exports.sendAdminNotification = exports.searchAdminNotificationRecipients = exports.previewAdminNotificationRecipients = exports.sendDoctorDailyReports = exports.resyncUserNotificationSchedules = exports.deliverScheduledNotifications = exports.onNotificationCreated = exports.setDoctorAvailabilityByAdmin = exports.setDoctorAvailability = exports.reviewDoctorAvailabilityRequest = exports.requestDoctorUnavailable = exports.updateDepartment = exports.setDepartmentActiveStatus = exports.deleteDepartment = exports.createDepartment = exports.updateUserProfileByAdmin = exports.unlinkGoogleProviderByAdmin = exports.setUserActiveStatus = exports.deleteUserAccount = exports.createUserAccount = exports.changeUserRoleByAdmin = exports.bootstrapSelfUserDocument = exports.completeInitialPasswordChange = exports.updateDoctorSchedule = exports.updateDoctorProfile = exports.updateDoctorEmail = exports.setDoctorActiveStatus = exports.resetDoctorPassword = exports.deleteDoctorAccount = exports.createDoctorAccount = exports.updateMedicalNotes = exports.updateAppointmentStatus = exports.rescheduleAppointment = exports.incrementQrScanFailures = exports.deleteAppointment = exports.createAppointment = exports.cancelAppointment = void 0;
var appointments_1 = require("./appointments");
Object.defineProperty(exports, "cancelAppointment", { enumerable: true, get: function () { return appointments_1.cancelAppointment; } });
Object.defineProperty(exports, "createAppointment", { enumerable: true, get: function () { return appointments_1.createAppointment; } });
Object.defineProperty(exports, "deleteAppointment", { enumerable: true, get: function () { return appointments_1.deleteAppointment; } });
Object.defineProperty(exports, "incrementQrScanFailures", { enumerable: true, get: function () { return appointments_1.incrementQrScanFailures; } });
Object.defineProperty(exports, "rescheduleAppointment", { enumerable: true, get: function () { return appointments_1.rescheduleAppointment; } });
Object.defineProperty(exports, "updateAppointmentStatus", { enumerable: true, get: function () { return appointments_1.updateAppointmentStatus; } });
Object.defineProperty(exports, "updateMedicalNotes", { enumerable: true, get: function () { return appointments_1.updateMedicalNotes; } });
var doctors_1 = require("./doctors");
Object.defineProperty(exports, "createDoctorAccount", { enumerable: true, get: function () { return doctors_1.createDoctorAccount; } });
Object.defineProperty(exports, "deleteDoctorAccount", { enumerable: true, get: function () { return doctors_1.deleteDoctorAccount; } });
Object.defineProperty(exports, "resetDoctorPassword", { enumerable: true, get: function () { return doctors_1.resetDoctorPassword; } });
Object.defineProperty(exports, "setDoctorActiveStatus", { enumerable: true, get: function () { return doctors_1.setDoctorActiveStatus; } });
Object.defineProperty(exports, "updateDoctorEmail", { enumerable: true, get: function () { return doctors_1.updateDoctorEmail; } });
Object.defineProperty(exports, "updateDoctorProfile", { enumerable: true, get: function () { return doctors_1.updateDoctorProfile; } });
Object.defineProperty(exports, "updateDoctorSchedule", { enumerable: true, get: function () { return doctors_1.updateDoctorSchedule; } });
var users_1 = require("./users");
Object.defineProperty(exports, "completeInitialPasswordChange", { enumerable: true, get: function () { return users_1.completeInitialPasswordChange; } });
Object.defineProperty(exports, "bootstrapSelfUserDocument", { enumerable: true, get: function () { return users_1.bootstrapSelfUserDocument; } });
Object.defineProperty(exports, "changeUserRoleByAdmin", { enumerable: true, get: function () { return users_1.changeUserRoleByAdmin; } });
Object.defineProperty(exports, "createUserAccount", { enumerable: true, get: function () { return users_1.createUserAccount; } });
Object.defineProperty(exports, "deleteUserAccount", { enumerable: true, get: function () { return users_1.deleteUserAccount; } });
Object.defineProperty(exports, "setUserActiveStatus", { enumerable: true, get: function () { return users_1.setUserActiveStatus; } });
Object.defineProperty(exports, "unlinkGoogleProviderByAdmin", { enumerable: true, get: function () { return users_1.unlinkGoogleProviderByAdmin; } });
Object.defineProperty(exports, "updateUserProfileByAdmin", { enumerable: true, get: function () { return users_1.updateUserProfileByAdmin; } });
var departments_1 = require("./departments");
Object.defineProperty(exports, "createDepartment", { enumerable: true, get: function () { return departments_1.createDepartment; } });
Object.defineProperty(exports, "deleteDepartment", { enumerable: true, get: function () { return departments_1.deleteDepartment; } });
Object.defineProperty(exports, "setDepartmentActiveStatus", { enumerable: true, get: function () { return departments_1.setDepartmentActiveStatus; } });
Object.defineProperty(exports, "updateDepartment", { enumerable: true, get: function () { return departments_1.updateDepartment; } });
var doctorAvailability_1 = require("./doctorAvailability");
Object.defineProperty(exports, "requestDoctorUnavailable", { enumerable: true, get: function () { return doctorAvailability_1.requestDoctorUnavailable; } });
Object.defineProperty(exports, "reviewDoctorAvailabilityRequest", { enumerable: true, get: function () { return doctorAvailability_1.reviewDoctorAvailabilityRequest; } });
Object.defineProperty(exports, "setDoctorAvailability", { enumerable: true, get: function () { return doctorAvailability_1.setDoctorAvailability; } });
Object.defineProperty(exports, "setDoctorAvailabilityByAdmin", { enumerable: true, get: function () { return doctorAvailability_1.setDoctorAvailabilityByAdmin; } });
var delivery_1 = require("./notifications/delivery");
Object.defineProperty(exports, "onNotificationCreated", { enumerable: true, get: function () { return delivery_1.onNotificationCreated; } });
var scheduled_1 = require("./notifications/scheduled");
Object.defineProperty(exports, "deliverScheduledNotifications", { enumerable: true, get: function () { return scheduled_1.deliverScheduledNotifications; } });
Object.defineProperty(exports, "resyncUserNotificationSchedules", { enumerable: true, get: function () { return scheduled_1.resyncUserNotificationSchedules; } });
Object.defineProperty(exports, "sendDoctorDailyReports", { enumerable: true, get: function () { return scheduled_1.sendDoctorDailyReports; } });
var admin_1 = require("./notifications/admin");
Object.defineProperty(exports, "previewAdminNotificationRecipients", { enumerable: true, get: function () { return admin_1.previewAdminNotificationRecipients; } });
Object.defineProperty(exports, "searchAdminNotificationRecipients", { enumerable: true, get: function () { return admin_1.searchAdminNotificationRecipients; } });
Object.defineProperty(exports, "sendAdminNotification", { enumerable: true, get: function () { return admin_1.sendAdminNotification; } });
Object.defineProperty(exports, "sendTopicNotification", { enumerable: true, get: function () { return admin_1.sendTopicNotification; } });
var admin_2 = require("./admin");
Object.defineProperty(exports, "assignSuperAdminSlot", { enumerable: true, get: function () { return admin_2.assignSuperAdminSlot; } });
Object.defineProperty(exports, "changeAdminRole", { enumerable: true, get: function () { return admin_2.changeAdminRole; } });
Object.defineProperty(exports, "createAdminAccount", { enumerable: true, get: function () { return admin_2.createAdminAccount; } });
Object.defineProperty(exports, "deleteAdminAccount", { enumerable: true, get: function () { return admin_2.deleteAdminAccount; } });
Object.defineProperty(exports, "forceSignOutUser", { enumerable: true, get: function () { return admin_2.forceSignOutUser; } });
Object.defineProperty(exports, "listAdminAuditLogs", { enumerable: true, get: function () { return admin_2.listAdminAuditLogs; } });
Object.defineProperty(exports, "resetAdminPassword", { enumerable: true, get: function () { return admin_2.resetAdminPassword; } });
Object.defineProperty(exports, "rotateSuperAdminSlot", { enumerable: true, get: function () { return admin_2.rotateSuperAdminSlot; } });
Object.defineProperty(exports, "setAdminActiveStatus", { enumerable: true, get: function () { return admin_2.setAdminActiveStatus; } });
Object.defineProperty(exports, "setAdminPermissions", { enumerable: true, get: function () { return admin_2.setAdminPermissions; } });
//# sourceMappingURL=index.js.map