import 'package:flutter/material.dart';

/// Shared icon options for departments across admin and patient screens.
const Map<String, IconData> departmentIcons = {
  // Popular hospital departments
  'cardiology': Icons.monitor_heart,
  'neurology': Icons.psychology,
  'pediatrics': Icons.child_care,
  'maternity': Icons.pregnant_woman,
  'ophthalmology': Icons.visibility,
  'orthopedics': Icons.accessibility_new,
  'emergency': Icons.emergency,
  'surgery': Icons.content_cut,
  'dermatology': Icons.face,
  'laboratory': Icons.biotech,
  'radiology': Icons.science,
  'pharmacy': Icons.local_pharmacy,
  'physiotherapy': Icons.fitness_center,
  'ent': Icons.hearing,
  'nutrition': Icons.restaurant,
  'dental': Icons.masks,
  'general': Icons.local_hospital,
  'telemedicine': Icons.video_camera_front,
  'administration': Icons.admin_panel_settings,
  'pulmonology': Icons.air,
  'oncology': Icons.coronavirus,
  'gastroenterology': Icons.lunch_dining,
  'urology': Icons.water_drop,
  'nephrology': Icons.opacity,
  'hematology': Icons.bloodtype,
  'psychiatry': Icons.self_improvement,
  'neonatology': Icons.child_friendly,
  'icu': Icons.monitor,
  'pain_management': Icons.healing,
  'pathology': Icons.biotech,
  'allergy': Icons.spa,
  'infectious_disease': Icons.bug_report,
  'endocrinology': Icons.thermostat,
  'burn_unit': Icons.local_fire_department,
  'rehabilitation': Icons.directions_walk,
  'dialysis': Icons.invert_colors,
  'transfusion': Icons.bloodtype,
  'ambulance': Icons.local_shipping,
  'palliative_care': Icons.volunteer_activism,
  'sports_medicine': Icons.sports_gymnastics,
  'sleep_medicine': Icons.nightlight,
  'genetics': Icons.hub,
  'trauma': Icons.personal_injury,
  'wound_care': Icons.healing,
  'geriatrics': Icons.elderly,
  'anesthesiology': Icons.airline_seat_flat,
  'rheumatology': Icons.accessibility,

  // Medical and health
  'medical_services': Icons.medical_services,
  'medication': Icons.medication,
  'medication_liquid': Icons.medication_liquid,
  'vaccines': Icons.vaccines,
  'health_and_safety': Icons.health_and_safety,
  'medical_info': Icons.medical_information,
  'emergency_share': Icons.emergency_share,
  'heart_broken': Icons.heart_broken,
  'monitor_heart': Icons.monitor_heart,
  'pill': Icons.medication,

  // Body and care
  'favorite': Icons.favorite,
  'face_2': Icons.face_2,
  'face_3': Icons.face_3,
  'face_retouching': Icons.face_retouching_natural,
  'directions_run': Icons.directions_run,
  'sick': Icons.sick,
  'clean_hands': Icons.clean_hands,
  'baby_changing': Icons.baby_changing_station,
  'wc': Icons.wc,
  'body': Icons.boy,
  'woman': Icons.woman,
  'man': Icons.man,
  'ear': Icons.hearing,
  'eye': Icons.remove_red_eye,
  'brain': Icons.psychology_alt,
  'lungs': Icons.air,
  'bone': Icons.accessibility_new,
  'blood_pressure': Icons.speed,

  // Equipment and facilities
  'sanitizer': Icons.sanitizer,
  'scale': Icons.scale,
  'straighten': Icons.straighten,
  'king_bed': Icons.king_bed,
  'single_bed': Icons.single_bed,
  'wheelchair': Icons.wheelchair_pickup,
  'stethoscope': Icons.medical_services,
  'syringe': Icons.vaccines,
  'device_thermostat': Icons.device_thermostat,
  'monitor_weight': Icons.monitor_weight,
  'bloodmonitor': Icons.monitor_weight,
  'local_laundry': Icons.local_laundry_service,
  'shower': Icons.shower,
  'bathtub': Icons.bathtub,

  // Research and analytics
  'memory': Icons.memory,
  'analytics': Icons.analytics,
  'insights': Icons.insights,
  'query_stats': Icons.query_stats,
  'data_exploration': Icons.data_exploration,
  'biotech': Icons.biotech,
  'microscope_alt': Icons.science,

  // Places and building
  'apartment': Icons.apartment,
  'meeting_room': Icons.meeting_room,
  'storefront': Icons.storefront,
  'home_health': Icons.home,
  'room_service': Icons.room_service,
  'domain': Icons.domain,
  'business': Icons.business,
  'location_city': Icons.location_city,
  'local_hospital_alt': Icons.local_hospital,

  // People and groups
  'groups': Icons.groups,
  'diversity_1': Icons.diversity_1,
  'diversity_2': Icons.diversity_2,
  'diversity_3': Icons.diversity_3,
  'person': Icons.person,
  'family_restroom': Icons.family_restroom,
  'people': Icons.people,
  'supervisor_account': Icons.supervisor_account,
  'support_agent': Icons.support_agent,
  'engineering': Icons.engineering,

  // General and symbols
  'star': Icons.star,
  'shield': Icons.shield,
  'verified': Icons.verified,
  'lightbulb': Icons.lightbulb,
  'bolt': Icons.bolt,
  'eco': Icons.eco,
  'pets': Icons.pets,
  'palette': Icons.palette,
  'email': Icons.email,
  'call': Icons.call,
  'notifications': Icons.notifications,
  'schedule': Icons.schedule,
  'event': Icons.event,
  'assignment': Icons.assignment,
  'description': Icons.description,
  'receipt_long': Icons.receipt_long,
  'task_alt': Icons.task_alt,
  'check_circle': Icons.check_circle,
  'info': Icons.info,
  'warning': Icons.warning,
  'help': Icons.help,
  'thumb_up': Icons.thumb_up,
  'flag': Icons.flag,
  'bookmark': Icons.bookmark,
  'grade': Icons.grade,
  'extension': Icons.extension,
  'settings': Icons.settings,
  'tune': Icons.tune,
  'build': Icons.build,
  'construction': Icons.construction,
};
